spring.application.name=ernst-young-app

# AWS conection properties / Need to update to make it work 
# or we can AwsConfig.java return null and comment all references and actions using s3Client in MetadataController.java
aws.access-key=YOUR_ACCESS_KEY
aws.secret-key=YOUR_SECRET_KEY
aws.region=us-east-1

resilience4j.retry.instances.s3Retry.max-attempts=3
resilience4j.retry.instances.s3Retry.wait-duration=500ms
resilience4j.retry.instances.s3Retry.enable-exponential-backoff=true
resilience4j.retry.instances.s3Retry.exponential-backoff-multiplier=2